### ISSUE TITLE
关于某些不兼容问题

### ISSUE THREAD

**Issue by ronething** [liuchengxu/szuthesis#5]
#4 

关于昨晚的错误原因 
```
Undefined control sequence. ^^I\tableofcontents
```
https://github.com/liuchengxu/szuthesis/blob/234f6b17b6b53a14d728f2be49e5b74ee507efa2/src/thesis/szutils.sty#L68

在 mac 下 `contentsname={目 \quad 录},` \quad  两边需要有空格，我更改之后就好了。

`\kaishu指导教师:\ 潘微科 \hspace{3cm}{ }`
`Undefined control sequence. ^^I\kaishu指导教师`
好像也是空格问题。
`\kaishu 指导教师:\ 潘微科 \hspace{3cm}{ }`

还有 `subspace.eps ` 为 0 KB 然后好像有点问题，
mac 下使用 
```
rm subspace.eps
convert subspace.png subspace.eps
```
解决。

还是谢谢一下提供了这么好的模版。谢谢 @liuchengxu

**Comment by liuchengxu** [comment]
@Lyrichu #3 可能是同样的问题，可以参考解决。
