### ISSUE TITLE
参考文献为问号

### ISSUE THREAD

**Issue by zhanghm1995** [liuchengxu/szuthesis#8]
非常感谢你能提供一个这么好的模板，给我学习LaTex提供了一个非常好的参考。

我使用的是TexMaker打开`main.tex`文件，也编译成功了，不过总是没有生成参考文献，文章中引用文献的地方也总是一个问号，能问下你知道这是怎么回事吗？
![1](https://user-images.githubusercontent.com/24753281/101238269-15d6ad00-371a-11eb-9104-57f63074a7c3.png)

**Comment by AirManH** [comment]
请提供 TexMaker 的编译指令

**Comment by zhanghm1995** [comment]
我是直接F1默认编译的，不知道怎么查看具体编译指令，我最后换成TexStudio了，这个可以
