### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by JCZ404** [liuchengxu/szuthesis#9]
非常感谢您能分享您的这份模板，对我学习LaTeX起到了很大的帮助！
有一个问题想问一下，就是我在win10+Texlive+Texstudio在编译您的工程时会报错，具体的错误如下图所示：
![image](https://user-images.githubusercontent.com/51013927/101327149-426cff00-38a9-11eb-93b1-14287c7f2185.png)
不知道这是什么原因呢？

**Comment by AirManH** [comment]
1. 请提供你的 texlive 版本和 texstudio 的编译指令。
2. 对于 `main.tex` 中的错误，请把 ` src/thesis/data/enabstract.tex` 中的 `\kaishu指导教师:\ 潘微科 \hspace{3cm}{ }` 改为 `\kaishu 指导教师:\ 潘微科 \hspace{3cm}{ }`。
3. 对于 `chapter04.tex` 中出现的错误 `Cannot determine size of graphic in ...`，请把 65 行的 `\includegraphics[width=3.5in]{subspace}` 改为 `\includegraphics[width=3.5in]{subspace.png}`。
4. 如果出现新的错误，你可以参考 [这个 pull request](https://github.com/liuchengxu/szuthesis/pull/7/files) 进行修复。
